### PR TITLE
Add possibility to refresh tokens without access token.

### PR DESCRIPTION
**Pull request by Bilanuk**
_And i also implemented my version of @hassanrbh PR(https://github.com/Gokul595/api_guard/pull/63)_
Still needs a lot of work to be prod ready. Just want to share my idea.

### CODE REVIEW

**Review by hassanrbh — COMMENTED** [review]
nice , a question is why you are storing both the access token and refresh token in the cookies ?

**Comment by Bilanuk** [comment]
> nice , a question is why you are storing both the access token and refresh token in the cookies ?

Sry for not replying for too long.
I decided to store in cookies just because i thougth it was more secure than just using JS to manipulate both of them. And it was much easier to handle with react and axios.
Today i did a little research and found that storing both tokens in cookies can lead to csrf attack. And storing in localstorage can lead to xss attack.
Also the creator of this gem pointed out the idea: https://github.com/Gokul595/api_guard/issues/47#issuecomment-813178698
I think that the best idea to store tokens is just to let the users of gem to decide where to store each token (body/header/cookie).
So they can use your strategy as well:
https://github.com/Gokul595/api_guard/pull/63#issuecomment-1320938964

**Comment by Bilanuk** [comment]
> > nice , a question is why you are storing both the access token and refresh token in the cookies ?
> 
> Sry for not replying for too long. I decided to store in cookies just because i thougth it was more secure than just using JS to manipulate both of them. And it was much easier to handle with react and axios. Today i did a little research and found that storing both tokens in cookies can lead to csrf attack. And storing in localstorage can lead to xss attack. Also the creator of this gem pointed out the idea: [#47 (comment)](https://github.com/Gokul595/api_guard/issues/47#issuecomment-813178698) I think that the best idea to store tokens is just to let the users of gem to decide where to store each token (body/header/cookie). So they can use your strategy as well: [#63 (comment)](https://github.com/Gokul595/api_guard/pull/63#issuecomment-1320938964)

@Gokul595 what you think about different strategies of storing tokens?

**Comment by hassanrbh** [comment]
hey @Bilanuk yeah that pretty nice idea, just let the client to choose his own strategy

**Pull request closed without merging**
