### PR TITLE
Authenticate and set multiple resources

### PR DESCRIPTION
**Pull request by MrChampz**
* Add support for `or` syntax in authentication method like:
```
before_action :authenticate_and_set_user_or_admin
```

* It is possible to use this syntax too:
```
before_action do
    authenticate_and_set_resources ["user", "admin"]
end
```

* Based on PR #26.

### CODE REVIEW

**Comment by Gokul595** [comment]
@MrChampz Thanks for this PR. The code changes and RSpec tests looks good 👍 

Can you please also add the docs for this syntax in readme? We can add it under [authenticate api request section](https://github.com/Gokul595/api_guard#authenticate-api-request).

**Note:** Let us keep `authenticate_and_set_resources ["user", "admin"]` syntax private and don't add this in readme, so that we no need to worry about changing the arguments or code of this method in future. Adding `authenticate_and_set_user_or_admin` syntax in readme is enough.

**Comment by MrChampz** [comment]
Thank you for the review! I'll do this ;)

**Comment by Gokul595** [comment]
Merged and released version 0.5.2. Thanks 👍

**Comment by jongirard** [comment]
Thank you for getting to this! 👏🏻

**Pull request merged**
